authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
     path('register/', views.register_view, name='register'),
     path('register/create/', views.register_create, name='register_create'),
     path('login/', views.login_view, name='login'),
     path('login/create/', views.login_create, name='login_create'),
     path('logout/', views.logout_view, name='logout'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path(
          'dashboard/sneaker/new/',
          views.DashboardSneaker.as_view(),
          name='dashboard_sneaker_new'
     ),
     path(
          'dashboard/sneaker/delete/',
          views.DashboardSneakerDelete.as_view(),
          name='dashboard_sneaker_delete'
     ),
     path(
          'dashboard/sneaker/<int:id>/edit/',
          views.DashboardSneaker.as_view(),
          name='dashboard_sneaker_edit'
     ),
     path(
          'profile/<int:id>/',
          views.ProfileView.as_view(),
          name='profile'
     ),
]

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# HTTP Request <- HTTP Response

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sneakers.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sneakers/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from sneakers import views

# sneakers:sneaker
app_name = 'sneakers'

sneaker_api_v2_router = SimpleRouter()
sneaker_api_v2_router.register(
    'sneakers/api/v2',
    views.SneakerAPIv2ViewSet,
    basename='sneakers-api'
)

urlpatterns = [
    path(
        '',
        views.SneakerListViewHome.as_view(),
        name="home"
    ),
    path(
        'sneakers/search/',
        views.SneakerListViewSearch.as_view(),
        name="search"
    ),
    path(
        'sneakers/category/<int:category_id>/',
        views.SneakerListViewCategory.as_view(),
        name="category"
    ),
    path(
        'sneakers/<int:pk>/',
        views.SneakerDetailView.as_view(),
        name="sneaker"
    ),
    path(
        'sneakers/api/v1/',
        views.SneakerListViewHomeAPI.as_view(),
        name="sneaker_api_v1"
    ),
    path(
        'sneakers/api/v1/<int:pk>/',
        views.SneakerDetailAPI.as_view(),
        name="sneaker_api_v1_detail"
    ),
    path(
        'sneakers/theory/',
        views.theory,
        name="theory"
    ),
    path(
        'sneakers/api/v2/profile/<int:pk>/',
        views.profile_api_detail,
        name="sneaker_api_v2_profile"
    ),
    path(
        'sneakers/api/token/',
        TokenObtainPairView.as_view(),
        name='token_obtain_pair'
    ),
    path(
        'sneakers/api/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh'
    ),
    path(
        'sneakers/api/token/verify/',
        TokenVerifyView.as_view(),
        name='token_verify'
    ),
]

urlpatterns += sneaker_api_v2_router.urls

authors/forms/sneaker_form.py
from collections import defaultdict

from authors.validators import AuthorsSneakerValidator
from django import forms
from django.core.exceptions import ValidationError
from sneakers.models import Sneaker
from utils.django_forms import add_attr


class AuthorsSneakerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)

        add_attr(self.fields.get('sneaker_description'), 'class', 'span-2')
        add_attr(self.fields.get('cover'), 'class', 'span-2')

    class Meta:
        model = Sneaker
        fields = 'title', 'description', 'condition_value', 'price', \
            'sneaker_description', 'cover'
        widgets = {
            'condition_value': forms.Select(
                choices=(
                    ('10', '10/10'),
                    ('9', '9/10'),
                    ('8', '8/10'),
                    ('7', '7/10'),
                    ('6', '6/10'),
                    ('5', '5/10'),
                    ('4', '4/10'),
                    ('3', '3/10'),
                    ('2', '2/10'),
                    ('1', '1/10'),
                )
            ),
        }

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        AuthorsSneakerValidator(self.cleaned_data, ErrorClass=ValidationError)
        return super_clean

sneakers/views.py
import os

from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import Http404, JsonResponse
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from utils.pagination import make_pagination

from sneakers.models import Sneaker

PER_PAGE = int(os.environ.get('PER_PAGE', 12))


def theory(request, *args, **kwargs):
    sneakers = Sneaker.objects.filter(
        Q(
            Q(
                title__icontains='sa',
                is_published=True,) |
            Q(
                id__gt=980
            )
        )
    )

    context = {
        'sneakers': sneakers
    }

    return render(
        request,
        'sneakers/pages/theory.html',
        context=context
    )


class SneakerListViewBase(ListView):
    model = Sneaker
    context_object_name = 'sneakers'
    paginate_by = None
    ordering = ['-id']
    template_name = 'sneakers/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.select_related('author', 'category')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('sneakers'),
            PER_PAGE
        )
        ctx.update(
            {'sneakers': page_obj, 'pagination_range': pagination_range}
        )
        return ctx


class SneakerListViewHome(SneakerListViewBase):
    template_name = 'sneakers/pages/home.html'


class SneakerListViewHomeAPI(SneakerListViewBase):
    template_name = 'sneakers/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        sneakers = self.get_context_data()['sneakers']
        sneakers_list = sneakers.object_list.values()

        return JsonResponse(
            list(sneakers_list),
            safe=False
        )


class SneakerListViewCategory(SneakerListViewBase):
    template_name = 'sneakers/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            category__id=self.kwargs.get('category_id'),
            is_published=True,
        ).order_by('-id')
        if not qs:
            raise Http404()
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'title': f'{ctx.get("sneakers")[0].category.name} - Category |'
        })
        return ctx


class SneakerListViewSearch(SneakerListViewBase):
    template_name = 'sneakers/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
            ),
            is_published=True,
            ).order_by('-id')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')
        ctx.update({
            'page_title': f'Search for "{search_term} "|',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })
        return ctx


class SneakerDetailView(DetailView):
    model = Sneaker
    context_object_name = 'sneaker'
    template_name = 'sneakers/pages/sneaker-view.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_page': True,
        })
        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs


class SneakerDetailAPI(SneakerDetailView):
    def render_to_response(self, context, **response_kwargs):
        sneaker = self.get_context_data()['sneaker']
        sneaker_dict = model_to_dict(sneaker)

        sneaker_dict['created_at'] = str(sneaker.created_at)

        if sneaker_dict.get('cover'):
            sneaker_dict['cover'] = self.request.build_absolute_uri() + \
                 sneaker_dict['cover'].url[1:]
        else:
            sneaker_dict['cover'] = ''

        del sneaker_dict['is_published']

        return JsonResponse(
            sneaker_dict,
            safe=False,
        )

sneakers/views/api.py
from authors.models import Profile
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from ..models import Sneaker
from ..serializers import ProfileSerializer, SneakerSerializer


class SneakerAPIv2Pagination(PageNumberPagination):
    page_size = 9


class SneakerAPIv2ViewSet(ModelViewSet):
    queryset = Sneaker.objects.get_published()
    serializer_class = SneakerSerializer
    pagination_class = SneakerAPIv2Pagination

    def get_queryset(self):
        qs = super().get_queryset()
        category_id = self.request.query_params.get('category_id', '')

        if category_id != '' and category_id.isnumeric():
            qs = qs.filter(category_id=category_id)

        return qs


@api_view()
def profile_api_detail(request, pk):
    profile = get_object_or_404(
        Profile.objects.all(),
        pk=pk
    )
    serializer = ProfileSerializer(
        instance=profile,
        many=False,
        context={'request': request},
    )
    return Response(serializer.data)

sneakers/views/site.py
import os

from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import Http404, JsonResponse
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from sneakers.models import Sneaker
from utils.pagination import make_pagination

PER_PAGE = int(os.environ.get('PER_PAGE', 12))


def theory(request, *args, **kwargs):
    sneakers = Sneaker.objects.only('id', 'title')

    context = {
        'sneakers': sneakers
    }

    return render(
        request,
        'sneakers/pages/theory.html',
        context=context
    )


class SneakerListViewBase(ListView):
    model = Sneaker
    context_object_name = 'sneakers'
    paginate_by = None
    ordering = ['-id']
    template_name = 'sneakers/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.select_related('author', 'category', 'author__profile')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('sneakers'),
            PER_PAGE
        )
        ctx.update(
            {'sneakers': page_obj, 'pagination_range': pagination_range}
        )
        return ctx


class SneakerListViewHome(SneakerListViewBase):
    template_name = 'sneakers/pages/home.html'


class SneakerListViewHomeAPI(SneakerListViewBase):
    template_name = 'sneakers/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        sneakers = self.get_context_data()['sneakers']
        sneakers_list = sneakers.object_list.values()

        return JsonResponse(
            list(sneakers_list),
            safe=False
        )


class SneakerListViewCategory(SneakerListViewBase):
    template_name = 'sneakers/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            category__id=self.kwargs.get('category_id'),
            is_published=True,
        ).order_by('-id')
        if not qs:
            raise Http404()
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'title': f'{ctx.get("sneakers")[0].category.name} - Category |'
        })
        return ctx


class SneakerListViewSearch(SneakerListViewBase):
    template_name = 'sneakers/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
            ),
            is_published=True,
            ).order_by('-id')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')
        ctx.update({
            'page_title': f'Search for "{search_term} "|',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })
        return ctx


class SneakerDetailView(DetailView):
    model = Sneaker
    context_object_name = 'sneaker'
    template_name = 'sneakers/pages/sneaker-view.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_page': True,
        })
        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs


class SneakerDetailAPI(SneakerDetailView):
    def render_to_response(self, context, **response_kwargs):
        sneaker = self.get_context_data()['sneaker']
        sneaker_dict = model_to_dict(sneaker)

        sneaker_dict['created_at'] = str(sneaker.created_at)

        if sneaker_dict.get('cover'):
            sneaker_dict['cover'] = self.request.build_absolute_uri() + \
                 sneaker_dict['cover'].url[1:]
        else:
            sneaker_dict['cover'] = ''

        del sneaker_dict['is_published']

        return JsonResponse(
            sneaker_dict,
            safe=False,
        )

sneakers/templates/sneakers/partials/head.html
{% load static %}


    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--awesome icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!--google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'sneakers/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">
    

sneakers/templates/sneakers/partials/sneakers.html
<div class="sneakers sneakers-list-item">
    <div class="sneakers-list-cover">
        <a href="{{ sneaker.get_absolute_url }}">
        <img src="{{ sneaker.cover.url }}" alt="Temporary image">
        </a>
    </div>

    <div class="sneaker-title-container">
        <h2 class="sneaker-title">
            <a href="{{ sneaker.get_absolute_url }}">
        {{ sneaker.title }}
            </a>
        </h2>
    </div>

    <div class="sneaker-author">
        {% if sneaker.author is not None %}
            <span class="sneaker-author-item">

                {% if sneaker.author.profile %}
                    <a href="{% url 'authors:profile' sneaker.author.profile.id%}">
                {% endif %}

                <i class="fas fa-user"></i>

                {% if sneaker.author.first_name %}
                    {{ sneaker.author.first_name }} {{ sneaker.author.last_name }}
                {% else %}
                    {{ sneaker.author.username }}
                {% endif %}         
                
                {% if sneaker.author.profile %}
                    </a>
                {% endif %}
            </span>
        {% endif %}

        <span class="sneaker-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ sneaker.created_at|date:"d/m/Y" }} às {{ sneaker.created_at|date:"H:i" }}
        </span>
        <span class="sneaker-author-item">
            <a href="{% url 'sneakers:category' sneaker.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ sneaker.category.name }}</span>
            </a>
        </span>
    </div>

    <div class="sneaker-content">
        <p>{{ sneaker.description }}</p>
    </div>

    <div class="sneaker-meta-container">
        <div class="sneaker-meta sneaker-condition">
            <h3 class="sneaker-meta-title"><i class="fas fa-star"></i> Condição</h3>
            <div class="sneaker-meta-text">
                {{ sneaker.condition_value }}{{ sneaker.condition_unit }}
            </div>
        </div>
        <div class="sneaker-meta sneaker-price">
            <h3 class="sneaker-meta-title"><i class="fas fa-dollar-sign"></i> Preço</h3>
            <div class="sneaker-meta-text">
                {{ sneaker.price_unit }} {{ sneaker.price }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="sneaker-footer">
        <a class="sneaker-read-more button button-dark button-full-width" href="{% url 'sneakers:sneaker' sneaker.id %}">
            <i class="fas fa-eye"></i>
            <span>Ver mais..</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {%if sneaker.sneaker_description_is_html is True %}
                {{ sneaker.sneaker_description|safe }}
            {% else %}
                {{ sneaker.sneaker_description|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>